import { Injectable } from '@nestjs/common';
import { OpenAPIObject } from '@nestjs/swagger';

// Endpoints only accessible to company admins
const COMPANY_ONLY = new Set([
  '/api/v1/schools',
  '/api/v1/schools/{id}',
  '/api/v1/subscriptions',
  '/api/v1/load-test.js',
]);

// Endpoints that may return 404 legitimately
const ALLOW_404 = new Set([
  '/api/v1/academic-years/current',
  '/api/v1/subscriptions/my',
  '/api/v1/subscriptions/{id}',
  '/api/v1/subscriptions/{id}/payments',
]);

// No auth required
const NO_AUTH = new Set(['/health', '/ready']);

// Map path → which list endpoint provides the ID for path params
const PARAM_SOURCE: Record<string, Record<string, string>> = {
  '/api/v1/academic-years/{id}':         { id: '/api/v1/academic-years' },
  '/api/v1/classes/{id}':                { id: '/api/v1/classes' },
  '/api/v1/sections/{id}':               { id: '/api/v1/sections' },
  '/api/v1/subjects/{id}':               { id: '/api/v1/subjects' },
  '/api/v1/students/{id}':               { id: '/api/v1/students' },
  '/api/v1/students/{id}/documents':     { id: '/api/v1/students' },
  '/api/v1/students/{id}/parents':       { id: '/api/v1/students' },
  '/api/v1/subscriptions/{id}':          { id: '/api/v1/subscriptions/my' },
  '/api/v1/subscriptions/{id}/payments': { id: '/api/v1/subscriptions/my' },
};

@Injectable()
export class LoadTestService {
  private document: OpenAPIObject | null = null;

  setDocument(doc: OpenAPIObject) {
    this.document = doc;
  }

  generate(scenario: 'smoke' | 'full' = 'smoke'): string {
    if (!this.document) return '// Swagger document not loaded';

    const paths = this.document.paths || {};
    const groups: Record<string, Array<{
      path: string;
      pathParams: string[];
      needsAuth: boolean;
      allow404: boolean;
    }>> = {};

    for (const [epPath, methods] of Object.entries(paths)) {
      const m = methods as Record<string, any>;
      if (!m.get) continue;
      if (COMPANY_ONLY.has(epPath)) continue;

      const info = m.get;
      const tag: string = (info.tags?.[0] as string) ?? 'Other';
      const pathParams: string[] = ((info.parameters ?? []) as any[])
        .filter((p: any) => p.in === 'path')
        .map((p: any) => p.name as string);

      if (!groups[tag]) groups[tag] = [];
      groups[tag].push({
        path: epPath,
        pathParams,
        needsAuth: !NO_AUTH.has(epPath),
        allow404: ALLOW_404.has(epPath),
      });
    }

    const lines: string[] = [];
    lines.push(`// AUTO-GENERATED by LoadTestService — do not edit manually`);
    lines.push(`// Re-generate: GET /load-test.js`);
    lines.push(`// Generated: ${new Date().toISOString()}`);
    lines.push(``);
    lines.push(`import http from 'k6/http';`);
    lines.push(`import { check, group, sleep } from 'k6';`);
    lines.push(`import { Rate, Trend } from 'k6/metrics';`);
    lines.push(``);
    lines.push(`const errorRate   = new Rate('errors');`);
    lines.push(`const listLatency = new Trend('latency_list', true);`);
    lines.push(`const authLatency = new Trend('latency_auth', true);`);
    lines.push(``);
    lines.push(`const BASE_URL         = __ENV.BASE_URL         || 'http://localhost:3000';`);
    lines.push(`const SCHOOL_DIAL_CODE = __ENV.SCHOOL_DIAL_CODE || '+91';`);
    lines.push(`const SCHOOL_PHONE     = __ENV.SCHOOL_PHONE     || '9999999999';`);
    lines.push(`const SCHOOL_PASSWORD  = __ENV.SCHOOL_PASSWORD  || 'Test@1234';`);
    lines.push(`const SCENARIO         = __ENV.K6_SCENARIO      || '${scenario}';`);
    lines.push(``);
    lines.push(`export const options = {`);
    lines.push(`  scenarios: SCENARIO === 'smoke' ? {`);
    lines.push(`    smoke: { executor: 'constant-vus', vus: 3, duration: '1m', tags: { scenario: 'smoke' } },`);
    lines.push(`  } : {`);
    lines.push(`    warmup: {`);
    lines.push(`      executor: 'ramping-vus', startVUs: 0,`);
    lines.push(`      stages: [{ duration: '30s', target: 5 }, { duration: '30s', target: 5 }, { duration: '10s', target: 0 }],`);
    lines.push(`      gracefulRampDown: '10s', tags: { scenario: 'warmup' },`);
    lines.push(`    },`);
    lines.push(`    sustained: {`);
    lines.push(`      executor: 'constant-vus', vus: 20, duration: '3m',`);
    lines.push(`      startTime: '1m20s', tags: { scenario: 'sustained' },`);
    lines.push(`    },`);
    lines.push(`    spike: {`);
    lines.push(`      executor: 'ramping-vus', startVUs: 0,`);
    lines.push(`      stages: [{ duration: '10s', target: 50 }, { duration: '30s', target: 50 }, { duration: '10s', target: 0 }],`);
    lines.push(`      startTime: '5m', tags: { scenario: 'spike' },`);
    lines.push(`    },`);
    lines.push(`  },`);
    lines.push(`  thresholds: {`);
    lines.push(`    http_req_duration: ['p(95)<2000', 'p(99)<4000'],`);
    lines.push(`    http_req_failed:   ['rate<0.20'],`);
    lines.push(`    errors:            ['rate<0.05'],`);
    lines.push(`    latency_list:      ['p(95)<2000'],`);
    lines.push(`    latency_auth:      ['p(95)<2000'],`);
    lines.push(`  },`);
    lines.push(`};`);
    lines.push(``);
    lines.push(`let vuToken = null;`);
    lines.push(`let vuRefreshToken = null;`);
    lines.push(`let vuTokenExpiry = 0;`);
    lines.push(``);
    lines.push(`export function setup() {`);
    lines.push(`  const res = http.post(`);
    lines.push(`    \`\${BASE_URL}/api/v1/auth/school/login\`,`);
    lines.push(`    JSON.stringify({ dial_code: SCHOOL_DIAL_CODE, phone_number: SCHOOL_PHONE, password: SCHOOL_PASSWORD }),`);
    lines.push(`    { headers: { 'Content-Type': 'application/json' } },`);
    lines.push(`  );`);
    lines.push(`  const ok = check(res, { 'setup: login 200': (r) => r.status === 200 });`);
    lines.push(`  if (!ok) { console.error(\`Login failed [\${res.status}]: \${res.body}\`); return {}; }`);
    lines.push(`  const b = JSON.parse(res.body).data;`);
    lines.push(`  return { token: b.accessToken, refreshToken: b.refreshToken, expiresAt: Date.now() + 14 * 60 * 1000 };`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`function getToken(data) {`);
    lines.push(`  if (!vuToken) { vuToken = data.token; vuRefreshToken = data.refreshToken; vuTokenExpiry = data.expiresAt; }`);
    lines.push(`  if (Date.now() >= vuTokenExpiry - 30000) {`);
    lines.push(`    const res = http.post(\`\${BASE_URL}/api/v1/auth/refresh\`, null,`);
    lines.push(`      { headers: { Authorization: \`Bearer \${vuRefreshToken}\`, 'Content-Type': 'application/json' } });`);
    lines.push(`    if (res.status === 200) {`);
    lines.push(`      const b = JSON.parse(res.body).data;`);
    lines.push(`      vuToken = b.accessToken; vuRefreshToken = b.refreshToken; vuTokenExpiry = Date.now() + 14 * 60 * 1000;`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(`  return vuToken;`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`function h(token) {`);
    lines.push(`  return { headers: { Authorization: \`Bearer \${token}\`, 'Content-Type': 'application/json' } };`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export default function (data) {`);
    lines.push(`  if (!data.token) { sleep(1); return; }`);
    lines.push(`  const token = getToken(data);`);
    lines.push(``);

    for (const [tag, endpoints] of Object.entries(groups)) {
      const idVars = new Set<string>();
      for (const ep of endpoints) {
        for (const param of ep.pathParams) {
          const v = this.resolveVar(ep.path, param);
          if (v) idVars.add(v);
        }
      }

      lines.push(`  // ── ${tag}`);
      if (idVars.size > 0) lines.push(`  let ${[...idVars].join(', ')} = null;`);
      lines.push(`  group('${tag.toLowerCase().replace(/\s+/g, '-')}', () => {`);
      lines.push(`    let r;`);

      for (const ep of endpoints) {
        const { path: epPath, pathParams, needsAuth, allow404 } = ep;
        const requiredVars = pathParams.map(p => this.resolveVar(epPath, p)).filter(Boolean) as string[];
        const authArg = needsAuth ? `, h(token)` : ``;
        const statusCheck = allow404
          ? `(res) => res.status === 200 || res.status === 404`
          : `(res) => res.status === 200`;

        let urlExpr = `\`\${BASE_URL}${epPath}\``;
        for (const param of pathParams) {
          const v = this.resolveVar(epPath, param) ?? param;
          urlExpr = urlExpr.replace(`{${param}}`, `\${${v}}`);
        }

        const guard = requiredVars.length > 0 ? `if (${requiredVars.join(' && ')}) ` : '';
        const isListEndpoint = pathParams.length === 0 && !epPath.includes('current') && !epPath.includes('/my');

        lines.push(``);
        lines.push(`    ${guard}{`);
        lines.push(`      r = http.get(${urlExpr}${authArg});`);
        if (isListEndpoint && needsAuth) lines.push(`      listLatency.add(r.timings.duration);`);
        if (tag === 'Auth') lines.push(`      authLatency.add(r.timings.duration);`);
        lines.push(`      check(r, { '${epPath.replace(/'/g, "\\'")}': ${statusCheck} });`);
        if (!allow404) lines.push(`      errorRate.add(r.status !== 200 && r.status !== 404);`);

        // Capture ID from list response
        const varName = this.pathToVar(epPath) + 'Id';
        if (idVars.has(varName) && pathParams.length === 0) {
          lines.push(`      try { ${varName} = JSON.parse(r.body)?.data?.[0]?.id; } catch {}`);
        }
        if (epPath === '/api/v1/subscriptions/my' && idVars.has('subscriptionId')) {
          lines.push(`      try { subscriptionId = JSON.parse(r.body)?.data?.id; } catch {}`);
        }
        lines.push(`    }`);
      }

      lines.push(`  });`);
      lines.push(`  sleep(0.2);`);
      lines.push(``);
    }

    lines.push(`  sleep(1);`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export function teardown(data) {`);
    lines.push(`  if (!data.token) return;`);
    lines.push(`  http.post(\`\${BASE_URL}/api/v1/auth/logout\`, null, h(data.token));`);
    lines.push(`}`);

    return lines.join('\n');
  }

  private pathToVar(p: string): string {
    return p
      .replace(/^\/api\/v1\//, '')
      .replace(/[{}\\/\-]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '');
  }

  private resolveVar(epPath: string, paramName: string): string | null {
    const src = PARAM_SOURCE[epPath];
    if (!src?.[paramName]) return null;
    const listPath = src[paramName];
    if (listPath === '/api/v1/subscriptions/my') return 'subscriptionId';
    return this.pathToVar(listPath) + 'Id';
  }
}
