export enum EnquiryAction {
  NEW_ENQUIRY = 'NEW_ENQUIRY',
  FOLLOW_UP_UPDATED = 'FOLLOW_UP_UPDATED',
  ADMISSION_CONFIRMED = 'ADMISSION_CONFIRMED',
  ENQUIRY_REJECTED = 'ENQUIRY_REJECTED',
  REMARKS_UPDATED = 'REMARKS_UPDATED',
  TEACHER_ASSIGNED = 'TEACHER_ASSIGNED',
  NEXT_FOLLOW_UP_UPDATE = 'NEXT_FOLLOW_UP_UPDATE',
}

export enum EnquiryStatus {
  NEW = 'NEW',
  FOLLOW_UP = 'FOLLOW_UP',
  ADMISSION_CONFIRMED = 'ADMISSION_CONFIRMED',
  REJECTED = 'REJECTED',
}
