export enum EnquiryAction {
  NEW_ENQUIRY = 'NEW_ENQUIRY',
  NEXT_FOLLOW_UP_UPDATE = 'NEXT_FOLLOW_UP_UPDATE',
  ADMISSION_CONFIRMED = 'ADMISSION_CONFIRMED',
  ENQUIRY_REJECTED = 'ENQUIRY_REJECTED',
}

export enum EnquiryStatus {
  NEW = 'NEW',
  FOLLOW_UP = 'FOLLOW_UP',
  ADMISSION_CONFIRMED = 'ADMISSION_CONFIRMED',
  REJECTED = 'REJECTED',
}
