export enum DocumentType {
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  TRANSFER_CERTIFICATE = 'TRANSFER_CERTIFICATE',
  AADHAAR = 'AADHAAR',
  PHOTO = 'PHOTO',
  MEDICAL_CERTIFICATE = 'MEDICAL_CERTIFICATE',
  CASTE_CERTIFICATE = 'CASTE_CERTIFICATE',
  INCOME_CERTIFICATE = 'INCOME_CERTIFICATE',
  PREVIOUS_MARKSHEET = 'PREVIOUS_MARKSHEET',
  OTHER = 'OTHER',
}

export enum BoardType {
  CBSE = 'CBSE',
  ICSE = 'ICSE',
  STATE = 'STATE',
  IB = 'IB',
  IGCSE = 'IGCSE',
}

export enum MarkingSystem {
  MARKS = 'MARKS',
  GRADES = 'GRADES',
  CGPA = 'CGPA',
}
