export enum StudentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  TRANSFERRED = 'TRANSFERRED',
  GRADUATED = 'GRADUATED',
  DROPPED = 'DROPPED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum BloodGroup {
  A_POSITIVE = 'A_POSITIVE',
  A_NEGATIVE = 'A_NEGATIVE',
  B_POSITIVE = 'B_POSITIVE',
  B_NEGATIVE = 'B_NEGATIVE',
  O_POSITIVE = 'O_POSITIVE',
  O_NEGATIVE = 'O_NEGATIVE',
  AB_POSITIVE = 'AB_POSITIVE',
  AB_NEGATIVE = 'AB_NEGATIVE',
}

export enum Religion {
  HINDU = 'HINDU',
  MUSLIM = 'MUSLIM',
  CHRISTIAN = 'CHRISTIAN',
  SIKH = 'SIKH',
  JAIN = 'JAIN',
  BUDDHIST = 'BUDDHIST',
  OTHER = 'OTHER',
}

export enum Category {
  GENERAL = 'GENERAL',
  OBC = 'OBC',
  SC = 'SC',
  ST = 'ST',
  OTHER = 'OTHER',
}

export enum ParentRelation {
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  GUARDIAN = 'GUARDIAN',
  GRANDPARENT = 'GRANDPARENT',
  SIBLING = 'SIBLING',
  OTHER = 'OTHER',
}

export enum Qualification {
  BELOW_10TH = 'BELOW_10TH',
  CLASS_10TH = 'CLASS_10TH',
  CLASS_12TH = 'CLASS_12TH',
  UNDERGRADUATE = 'UNDERGRADUATE',
  POSTGRADUATE = 'POSTGRADUATE',
  MASTERS = 'MASTERS',
  DOCTORATE = 'DOCTORATE',
  OTHER = 'OTHER',
}

export enum DocumentType {
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  TRANSFER_CERTIFICATE = 'TRANSFER_CERTIFICATE',
  AADHAAR = 'AADHAAR',
  PHOTO = 'PHOTO',
  MEDICAL_CERTIFICATE = 'MEDICAL_CERTIFICATE',
  CASTE_CERTIFICATE = 'CASTE_CERTIFICATE',
  INCOME_CERTIFICATE = 'INCOME_CERTIFICATE',
  PREVIOUS_MARKSHEET = 'PREVIOUS_MARKSHEET',
  MERIT_CERTIFICATE = 'MERIT_CERTIFICATE',
  REPORT = 'REPORT',
  OTHER = 'OTHER',
}

export enum DocumentFileType {
  PDF = 'PDF',
  IMAGE = 'IMAGE',
}